server:
  port: 8080
logging:
  level:
    root : INFO
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  http:
    encoding:
      charset: utf-8
      enabled: true
